// Generated by CoffeeScript 1.10.0
(function() {
  var Extractor, ExtractorJP2Kakadu;

  ExtractorJP2Kakadu = require('./extractors/extractor-jp2-kakadu').ExtractorJP2Kakadu;

  Extractor = (function() {
    function Extractor(options, final_callback) {
      this.options = options;
      this.final_callback = final_callback;
      this.extractor = new ExtractorJP2Kakadu(this.options, this.final_callback);
    }

    Extractor.prototype.extract = function() {
      return this.extractor.extract();
    };

    return Extractor;

  })();

  exports.Extractor = Extractor;

}).call(this);
