// Generated by CoffeeScript 1.10.0
(function() {
  var ExtractorJp2Kakadu, ExtractorJp2Openjpeg, extractor_creator;

  ExtractorJp2Kakadu = require('./extractors/extractor-jp2-kakadu').ExtractorJp2Kakadu;

  ExtractorJp2Openjpeg = require('./extractors/extractor-jp2-openjpeg').ExtractorJp2Openjpeg;

  extractor_creator = function(type) {
    var Extractor;
    return Extractor = (function() {
      function Extractor(options, final_callback) {
        this.options = options;
        this.final_callback = final_callback;
        this.extractor = type === 'kdu' ? new ExtractorJp2Kakadu(this.options, this.final_callback) : type === 'opj' ? new ExtractorJp2Openjpeg(this.options, this.final_callback) : void 0;
      }

      Extractor.prototype.extract = function() {
        return this.extractor.extract();
      };

      return Extractor;

    })();
  };

  exports.Extractor = extractor_creator;

}).call(this);
