// Generated by CoffeeScript 1.10.0
(function() {
  var enrich_params;

  enrich_params = function(params, info) {
    var centerx, centery, h, halfheight, halfwidth, percent_factor, region_width, w, x, y;
    if ((params.region.pctx != null) && (params.region.x == null)) {
      params.region.x = Math.round(info.width * (params.region.pctx / 100));
      params.region.y = Math.round(info.height * (params.region.pcty / 100));
      params.region.w = Math.round(info.width * (params.region.pctw / 100));
      params.region.h = Math.round(info.height * (params.region.pcth / 100));
    }
    if (params.region === 'square' || params.region === '!square' || params.region === 'square!') {
      if (info.width === info.height) {
        x = 0;
        y = 0;
        w = info.width;
        h = info.height;
      } else if (info.width < info.height) {
        x = 0;
        w = info.width;
        h = info.width;
        if (params.region === 'square') {
          centery = Math.round(info.height / 2);
          halfwidth = Math.round(info.width / 2);
          y = centery - halfwidth;
        } else if (params.region === '!square') {
          y = 0;
        } else if (params.region === 'square!') {
          y = info.height - info.width;
        }
      } else if (info.width > info.height) {
        y = 0;
        w = info.height;
        h = info.height;
        if (params.region === 'square') {
          centerx = Math.round(info.width / 2);
          halfheight = Math.round(info.height / 2);
          x = centerx - halfheight;
        } else if (params.region === '!square') {
          x = 0;
        } else if (params.region === 'square!') {
          x = info.width - info.height;
        }
      }
      params.region = {
        region_type: 'regionSquare'
      };
      params.region.x = x;
      params.region.y = y;
      params.region.w = w;
      params.region.h = h;
    }
    if (params.size.pct != null) {
      region_width = params.region === 'full' ? info.width : params.region.w;
      percent_factor = params.size.pct / 100;
      params.size.w = Math.round(region_width * percent_factor);
    }
    return params;
  };

  exports.enrich_params = enrich_params;

}).call(this);
