// Generated by CoffeeScript 1.10.0
(function() {
  var enrich_params;

  enrich_params = function(params, info) {
    var percent_factor, region_width;
    if ((params.region.pctx != null) && (params.region.x == null)) {
      params.region.x = Math.round(info.width * (params.region.pctx / 100));
      params.region.y = Math.round(info.height * (params.region.pcty / 100));
      params.region.w = Math.round(info.width * (params.region.pctw / 100));
      params.region.h = Math.round(info.height * (params.region.pcth / 100));
    }
    if (params.size.pct != null) {
      region_width = params.region === 'full' ? info.width : params.region.w;
      percent_factor = params.size.pct / 100;
      params.size.w = region_width * percent_factor;
    }
    return params;
  };

  exports.enrich_params = enrich_params;

}).call(this);
