// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    IIIFImageExtractor: require('./iiif-image-extractor').IIIFImageExtractor,
    IIIFImageRequestParser: require('./iiif-image-request-parser').IIIFImageRequestParser,
    IIIFImageInformer: require('./iiif-image-informer').IIIFImageInformer,
    IIIFInfoJSONCreator: require('./iiif-info-json-creator').IIIFInfoJSONCreator
  };

}).call(this);
