// Generated by CoffeeScript 1.10.0
(function() {
  var InformerJp2Kakadu, InformerJp2Openjpeg, informer_creator;

  InformerJp2Kakadu = require('./informers/informer-jp2-kakadu').InformerJp2Kakadu;

  InformerJp2Openjpeg = require('./informers/informer-jp2-openjpeg').InformerJp2Openjpeg;

  informer_creator = function(type) {
    var Informer;
    return Informer = (function() {
      function Informer(path, final_callback) {
        this.path = path;
        this.final_callback = final_callback;
        this.informer = type === 'kdu' ? new InformerJp2Kakadu(this.path, this.final_callback) : type === 'opj' ? new InformerJp2Openjpeg(this.path, this.final_callback) : void 0;
      }

      Informer.prototype.inform = function() {
        return this.informer.inform();
      };

      return Informer;

    })();
  };

  exports.Informer = informer_creator;

}).call(this);
