// Generated by CoffeeScript 1.10.0
(function() {
  var Informer, InformerJP2Kakadu;

  InformerJP2Kakadu = require('./informers/informer-jp2-kakadu').InformerJP2Kakadu;

  Informer = (function() {
    function Informer(path, final_callback) {
      this.path = path;
      this.final_callback = final_callback;
      this.informer = new InformerJP2Kakadu(this.path, this.final_callback);
    }

    Informer.prototype.inform = function() {
      return this.informer.inform();
    };

    return Informer;

  })();

  exports.Informer = Informer;

}).call(this);
